#!/bin/sh

# Specified tool version environment variables
#
ETCD_VERSION=${ETCD_VERSION:-'2.1.0-alpha.0'}
CONFD_VERSION=${CONFD_VERSION:-'0.9.0'}
ENVCONSUL_VERSION=${ENVCONSUL_VERSION:-'0.5.0'}

# Predefined URL endpoints
#
ETCD_URL="https://github.com/coreos/etcd/releases/download/v2.1.0-alpha.0/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz"
CONFD_URL="https://github.com/kelseyhightower/confd/releases/download/v0.9.0/confd-${CONFD_VERSION}-linux-amd64"
ENVCONSUL_URL="https://github.com/hashicorp/envconsul/releases/download/v0.5.0/envconsul_${ENVCONSUL_VERSION}_linux_amd64.tar.gz"

echo "Downloading and installing ETCD..."
curl -s -L -q "$ETCD_URL" | tar xz  --strip-components=1 -C /tools
if [ $? -eq 0 ]; then echo "ETCD Installed"; fi
echo "Downloading and installing ENVCONSUL..."
curl -s -L -q "$ENVCONSUL_URL" | tar xz  --strip-components=1 -C /tools 
if [ $? -eq 0 ]; then echo "ENVCONSUL Installed"; fi
echo "Downloading and installing CONFD..."
curl -s -L -o /tools/confd "$CONFD_URL"
if [ $? -eq 0 ]; then echo "CONFD Installed"; fi
